### ISSUE TITLE
Prevent child theme css file loading between unminified and minified parent theme css

### ISSUE THREAD

**Issue by liam-moore** [purothemes/polestar#1]
I'm using the polestar theme as a parent theme and I'm finding that I can't get a child theme css to display. I discovered that there appears to be an unminified and a minified css loading from the parent theme and when I enqueue the child css, it gets loaded between these two, thus rendering the child theme css irrelevant. It basically goes like:

```
<link rel='stylesheet' href='../polestar/style.css' />
<link rel='stylesheet' href='../polestar-child/style.css' />
<link rel='stylesheet' href='../polestar/style.min.css' />
```

I can't figure out to load the child theme css after the parent minified css, or better yet, not load both files. 

Could this be a polestar bug, or is there a trick I'm missing?

**Comment by Misplon** [comment]
Hi Liam

Thanks for reaching out. The unminified parent stylesheet is included in the parent theme folder to meet theme directory guidelines. Only the minified version is [enqueued](https://github.com/purothemes/polestar/blob/master/functions.php#L152).

If you setup your child theme stylesheet enqueue like this: https://github.com/purothemes/polestar-child/blob/master/functions.php and nothing else, you should land up with only the parent minified stylesheet and the child stylesheet as required.

**Comment by Misplon** [comment]
Let me know how it goes. We'll definitely solve this :)

**Comment by liam-moore** [comment]
Hi Andrew,

Thanks for the speedy reply! Just having bother getting the child theme to show up under a selectable theme – it's disappeared now where it was previously always there...

My folder structure:

```
wp-content > themes > polestar
wp-content > themes > polestar-child
```

And then the CSS info at the top of the file:

```
wp-content > themes > polestar-child > style.css
```

```
/*
Theme Name: Polestar Child
Description: Child theme edits to the Polestar parent theme.
Template: Polestar
*/
```

And then the PHP you provided in:

```
wp-content > themes > polestar-child > functions.php
```

```
<?php
/**
 * Enqueue theme scripts and styles.
 */
function polestar_child_scripts() {
	// Child theme stylesheet.
	wp_enqueue_style( 'polestar-child', get_stylesheet_directory_uri() . '/style.css' );
}
add_action( 'wp_enqueue_scripts', 'polestar_child_scripts', 8 );
```

Sorry for deviating from the original request/issue, but could the functions.php code be doing something!?

**Comment by Misplon** [comment]
Try:

`template: polestar`

[Ref](https://github.com/purothemes/polestar-child/blob/master/style.css).

**Comment by liam-moore** [comment]
Wow so lowercases ```template: polestar``` worked! I changed the 8 to 80 in:

```
add_action( 'wp_enqueue_scripts', 'polestar_child_scripts', 8 );
```

And that works, but now the css from my child theme is showing an older version of a file I uploaded. Tried clearing cache/different browser/etc. I can see in code inspector a version attached to the child theme css:

```
style.css?ver=4.9.2:9
```

Is there a way to prevent this too, or is this part of the polestar theme?

Thanks for your help on this!

**Comment by Misplon** [comment]
Glad to hear you've made progress :)

That's core behaviour. If no version number is appended, WP will append its own. If you want to append a version number you can do so.

`wp_enqueue_style( 'polestar-child', get_stylesheet_directory_uri() . '/style.css', array(), '1.0' );`

[Ref](https://developer.wordpress.org/reference/functions/wp_enqueue_style/).

For local development, make sure your localhost, MAMP etc. has opcache disabled. In MAMP it's at MAMP > Preferences > PHP > Cache > Off.

**Comment by liam-moore** [comment]
Hi Andrew,

Getting the child theme to load after the parent theme was giving me the most difficulty so thanks for your help on this (even if this thread turned more into more of a support ticket for other things)! Managed to find out I also wasn't in DEV Mode using Pagely's PressCACHE (rookie mistake) but everything is as it should be now.

Cheers

**Comment by Misplon** [comment]
Super :) Glad I could help. All the best with your upcoming project.
